---
title: "US Research University Prediction Model"
author: "Philip Gabriel Andrada"
date: "October 31, 2016"
output: word_document
---

#Preparation

```{r}
#loading necessary libraries
library(rpart)
library(randomForest)
library(caret)
library(Boruta)
library(e1071)
library(ROCR)
library(corrplot)
library(ggplot2)

#Reading Data Files
usuniv2010 <- read.csv("C:\\Users\\Philip\\Desktop\\Capstone\\MERGED2010_11_PP.csv")
usuniv2011 <- read.csv("C:\\Users\\Philip\\Desktop\\Capstone\\MERGED2011_12_PP.csv")
usuniv2012 <- read.csv("C:\\Users\\Philip\\Desktop\\Capstone\\MERGED2012_13_PP.csv")
usuniv2013 <- read.csv("C:\\Users\\Philip\\Desktop\\Capstone\\MERGED2013_14_PP.csv")
usuniv2014 <- read.csv("C:\\Users\\Philip\\Desktop\\Capstone\\MERGED2014_15_PP.csv")

#Binding All Data Files into One Data Frame
usuniv <- rbind(usuniv2010,usuniv2011,usuniv2012,usuniv2013,usuniv2014)

#Since there are some incomplete Carnegie Classifications, we use usuniv2014 as basis for the classification for the rest
usuniv$CCBASIC2 <- usuniv2014$CCBASIC[match(usuniv$OPEID6,usuniv2014$OPEID6)]

#added the ACCEPTED column for those that are research universities (CCBASIC2 is equal to 15 or 16), as our focus will be on these
usuniv$ACCEPTED <- ifelse(usuniv$CCBASIC2 %in% c(15,16), 1, 0)

#Create a vector with the columns that is needed from the study
# 19 - institution region (1-New England, 2-Mid East, 3-Great Lakes, 4-Plains, 5-Southeast, 6-Southwest, 7-Rocky Mountains, 8-Far West, 9-Outlying Areas)
# 37-38 - admission rate
# 39-61 - SAT and ACT Scores
# 62-99 - percentage of degrees awarded for each field of study
# 293-299 - total share of enrollment for different ethnicities
# 300 - total share of enrollment that are non-resident aliens (i.e. international students)
# 301 - total share of enrollment that have unknown race
# 314 - share of undergraduate, degree-/certificate-seeking students who are part-time
# 377 - average cost of attendance in an academic year institution
# 379 - in-state tuition and fees
# 380 - out-of-state tuition and fees
# 387 - completion rate of first-time, full-time students at four-year institutions with 150% of expected time to completion)
# 397-403 - completion rate for first-time, full-time students for different ethnicities
# 404 - completion rate for first-time, full-time students for non-resident aliens
# 405 - completion rate for first-time, full-time students that have unknown race
# 429 - retention rate for first-time, full time studnets at four-year institutions
# 438 - percent of all federal undergraduate students receiving a federal student loan
# 1412 - percentage of first-generation students
# 1740-1741 - total share of enrollment per gender
# 1745 - acceptance flag
col_select <- c(19,37:38,61:99,293:301,314,377,379:380,387,397:405,429,438,1412,1740:1741, 1744, 1745)

# Create a new data frame with the columns that will be filtered out
usunivfilter <- usuniv[,col_select]

# Change the factor columns to numeric for faster processing
for (i in 1:ncol(usunivfilter)){
  usunivfilter[,i] <- as.numeric(as.character(usunivfilter[,i]))
}

# Clean the results to have all complete 
usunivfilter <- usunivfilter[!is.na(usunivfilter$C150_4),]
usunivfilter <- usunivfilter[!is.na(usunivfilter$C150_4_ASIAN),]
usunivfilter <- usunivfilter[!is.na(usunivfilter$C150_4_WHITE),]
usunivfilter <- usunivfilter[!is.na(usunivfilter$C150_4_BLACK),]
usunivfilter <- usunivfilter[!is.na(usunivfilter$C150_4_NRA),]
usunivfilter <- usunivfilter[!is.na(usunivfilter$ADM_RATE_ALL),]
usunivfilter <- usunivfilter[!is.na(usunivfilter$SAT_AVG_ALL),]
usunivfilter <- usunivfilter[!is.na(usunivfilter$UGDS_ASIAN),]
usunivfilter <- usunivfilter[!is.na(usunivfilter$UGDS_WHITE),]
usunivfilter <- usunivfilter[!is.na(usunivfilter$UGDS_BLACK),]
usunivfilter <- usunivfilter[!is.na(usunivfilter$UGDS_NRA),]
usunivfilter <- usunivfilter[!is.na(usunivfilter$UGDS_WOMEN),]
usunivfilter <- usunivfilter[!is.na(usunivfilter$UGDS_MEN),]
usunivfilter <- usunivfilter[!is.na(usunivfilter$COSTT4_A),]
usunivfilter <- usunivfilter[!is.na(usunivfilter$PCIP11),]
usunivfilter <- usunivfilter[!is.na(usunivfilter$PCIP12),]
usunivfilter <- usunivfilter[!is.na(usunivfilter$PCIP14),]
usunivfilter <- usunivfilter[!is.na(usunivfilter$PCIP15),]
usunivfilter <- usunivfilter[!is.na(usunivfilter$PCIP24),]
usunivfilter <- usunivfilter[!is.na(usunivfilter$PCIP26),]
usunivfilter <- usunivfilter[!is.na(usunivfilter$PCIP27),]
usunivfilter <- usunivfilter[!is.na(usunivfilter$PCIP40),]
usunivfilter <- usunivfilter[!is.na(usunivfilter$PCIP45),]
usunivfilter <- usunivfilter[!is.na(usunivfilter$PCIP51),]
usunivfilter <- usunivfilter[!is.na(usunivfilter$PCIP52),]
usunivfilter <- usunivfilter[!is.na(usunivfilter$PCTFLOAN),]
usunivfilter <- usunivfilter[!is.na(usunivfilter$PPTUG_EF),]
usunivfilter <- usunivfilter[!is.na(usunivfilter$RET_FT4),]
usunivfilter <- usunivfilter[!is.na(usunivfilter$PAR_ED_PCT_1STGEN),]

#We will create another data frame for the research universities only
usresearchuniv <- usunivfilter[usunivfilter$CCBASIC2 %in% c(15,16),]
```

# Distributions and Box and Whisker Plots

```{r}
# Histogram of SAT Averages for US Colleges and Universities
hist(usunivfilter$SAT_AVG_ALL, main = "Histogram of SAT Averages for US Colleges and Universities", xlab="SAT Average")

# Histogram of SAT Averages for US Research Universities
hist(usresearchuniv$SAT_AVG_ALL, main = "Histogram of SAT Averages for US Colleges and Universities", xlab="SAT Average")

# Histogram of Admission Rates for US Research Universities
hist(usresearchuniv$ADM_RATE_ALL, main = "Histogram of Admission Rates for Research Universities", xlab = "Admission Rate (%)")

# Histogram of Women in US Research Universitie
hist(usresearchuniv$UGDS_WOMEN, main = "Histogram of Women in Research Universities", xlab = "Demographic of Women (%)")

# Boxplot of Completion Rates per Region in US Research Universities
boxplot(C150_4 ~ REGION, usresearchuniv, main = "Completion Rates in Research Universities per Region", col=c("red", "orange", "yellow", "green", "blue", "violet", "white", "gray", "magenta"), ylab = "Completion Rate", xlab = "Regions")

# Boxplot of COmpletion Rates of International Students per Region in US Research Universities
boxplot(C150_4_NRA ~ REGION, usresearchuniv, main = "Completion Rates of International Students in Research Universities Per Region", col=c("red", "orange", "yellow", "green", "blue", "violet", "white", "gray", "magenta"), ylab = "Completion Rate", xlab = "Regions")
```

#Correlations

```{r}
#Correlation between the SAT grades and the acceptance for the research universities
plot(usunivfilter$SAT_AVG_ALL, usunivfilter$ACCEPTED, main="SAT Average Grades vs. Acceptance to Research Universities", xlab="SAT Average Grades", ylab="Accepted (1 or 0)")

#Correlation between the admission rates and the acceptance for the research universities
plot(usunivfilter$ADM_RATE_ALL, usunivfilter$ACCEPTED, main="Admission Rates vs. Acceptance to Research Universities", xlab="Admission Rates (%)", ylab="Accepted (1 or 0)")

#Correlation between admission rate for research universities and program completion rate
plot(usresearchuniv$ADM_RATE_ALL, usresearchuniv$C150_4, main="Admission Rate vs. Program Completion Rate for Research Universities", xlab="Admission Rate (%)", ylab="Completion Rate (%)")

#Correlation between admission rate for research universities and program completion rate
plot(usresearchuniv$REGION, usresearchuniv$C150_4, main="Region vs. Program Completion Rate for Research Universities", xlab="Region Number", ylab="Completion Rate (%)")

#Correlation between attendees and completion rate of non-resident aliens (International Students)
plot(usresearchuniv$UGDS_NRA, usresearchuniv$C150_4_NRA, main="Percentage of Attendees vs. Completion Rates of International Students in Research Universities", xlab="Population Share of International Students (%)", ylab="Completion Rate of International Students (%)")

#Correlation between attendees and completion rate of 1st Generation students in Research Universities
plot(usresearchuniv$PAR_ED_PCT_1STGEN, usresearchuniv$C150_4, main="Percentage of Attendees vs. Completion Rates of 1st Generation Students in Research Universities", xlab="1st Year Generation Students (%)", ylab="Completion Rate (%)")

```

#U.S. Research University Acceptance Model

```{r}
# create a training and test model using a 75%/25% from the data set 
rm_train <- sample(nrow(usunivfilter), floor(nrow(usunivfilter)*0.75))
univ_train <- usunivfilter[rm_train,]
univ_test <- usunivfilter[-rm_train,]

# create a formula for the US research university acceptance model for International Students taking up Science degrees/majors
test_formulagen <- formula(ACCEPTED ~ REGION + ADM_RATE_ALL + SAT_AVG_ALL + PCIP11 + PCIP12 + PCIP14 + PCIP15 + PCIP24 + PCIP26 + PCIP27 + PCIP40 + PCIP45 + PCIP51 + PCIP52 + UGDS_NRA + UGDS_UNKN + COSTT4_A + PCTFLOAN +  UGDS_WOMEN)

# do a logistic regression model based on the formula created
model_glm <- glm(test_formulagen, data=univ_train,family=binomial())
summary(model_glm)

# do the testing with the prediction model
univ_test$scores <- predict(model_glm, type="response", newdata = univ_test)
pred <- prediction(univ_test$scores, univ_test$ACCEPTED)

# prepare confusion matrix to see the scores
c <- confusionMatrix(as.integer(univ_test$scores > 0.5), univ_test$ACCEPTED)
c$table

# show the curve on the performance
perf <- performance(pred,"tpr","fpr")
plot(perf, lty = 1)

# Now we check on what acceptable ways we could do for regression
#doing single decision tree
model_tree <- rpart(test_formulagen, method="anova",data = univ_train)
pred_tree <- predict(model_tree, newdata = univ_test)
accu = abs(pred_tree - univ_test$ACCEPTED) < 0.25
frac = sum(accu)/length(accu)
print(frac)

#doing random forest
model_forest <- randomForest(test_formulagen, data = univ_train)
pred_forest <- predict(model_forest, newdata = univ_test)
accu2 <- abs(pred_forest - univ_test$ACCEPTED) < 0.25
frac2 <- sum(accu2)/length(accu2)
print(frac2)

#doing support vector machine
model_svm <- svm(test_formulagen, data = univ_train)
pred_svm <- predict(model_svm, newdata = univ_test)
accu3 <- abs(pred_svm - univ_test$ACCEPTED) < 0.25
frac3 <- sum(accu3)/length(accu3)
print(frac3)

# We will consider all variables, and use Boruta to use what variables we could use for doing a better outcome of the moded

# First, we will create another copy of the dataset
usunivnoccbasic <- usunivfilter

# Next, we will change those that have "NA" to 0, since there is no data in it
usunivnoccbasic[usunivnoccbasic == "NA"] <- 0

# Next, we will choose rows that have complete cases
usunivnoccbasic <- usunivnoccbasic[complete.cases(usunivnoccbasic),]

# Now that we have the cleansed dataset, we will implement Boruta
boruta.train <- Boruta(ACCEPTED ~ .-CCBASIC2, data=usunivnoccbasic,doTrace = 2)
print(boruta.train)

# We will print the stats of the variables that would be accepted or not
stats <- attStats(boruta.train)
print(stats)
```

# US Research University Completion Rate Prediction Model

```{r}
rm_train2 <- sample(nrow(usresearchuniv), floor(nrow(usresearchuniv)*0.75))
univ_train2 <- usresearchuniv[rm_train2,]
univ_test2 <- usresearchuniv[-rm_train2,]

formula_completionrate <- formula(C150_4 ~ REGION + ADM_RATE_ALL + UGDS_NRA + PPTUG_EF + COSTT4_A + PCTFLOAN + PAR_ED_PCT_1STGEN)

model_tree2 <- rpart(formula_completionrate, method="anova",data = univ_train2)
pred_tree2 <- predict(model_tree2, newdata = univ_test2)
accu4 = abs(pred_tree2 - univ_test2$C150_4_NRA) < 0.25
frac4 = sum(accu4)/length(accu4)
print(frac4)

model_forest2 <- randomForest(formula_completionrate, data = univ_train2)
pred_forest2 <- predict(model_forest2, newdata = univ_test2)
accu5 <- abs(pred_forest2 - univ_test2$ACCEPTED) < 0.25
frac5 <- sum(accu5)/length(accu5)
print(frac5)

model_svm2 <- svm(formula_completionrate, data = univ_train2)
pred_svm2 <- predict(model_svm2, newdata = univ_test2)
accu6 <- abs(pred_svm2 - univ_test2$ACCEPTED) < 0.25
frac6 <- sum(accu6)/length(accu6)
print(frac6)
```